# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindowui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(893, 906)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableViewDevice = QtWidgets.QTableView(self.centralwidget)
        self.tableViewDevice.setGeometry(QtCore.QRect(10, 80, 511, 661))
        self.tableViewDevice.setObjectName("tableViewDevice")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 881, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditIP = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditIP.setObjectName("lineEditIP")
        self.horizontalLayout.addWidget(self.lineEditIP)
        self.pushBtnScanning = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushBtnScanning.setObjectName("pushBtnScanning")
        self.horizontalLayout.addWidget(self.pushBtnScanning)
        self.pushBtnClearDevice = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushBtnClearDevice.setObjectName("pushBtnClearDevice")
        self.horizontalLayout.addWidget(self.pushBtnClearDevice)
        self.pushBtnRepairTs = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushBtnRepairTs.setObjectName("pushBtnRepairTs")
        self.horizontalLayout.addWidget(self.pushBtnRepairTs)
        self.pushBtnCheckStatus = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushBtnCheckStatus.setObjectName("pushBtnCheckStatus")
        self.horizontalLayout.addWidget(self.pushBtnCheckStatus)
        self.cbCheckAllDevice = QtWidgets.QCheckBox(self.centralwidget)
        self.cbCheckAllDevice.setGeometry(QtCore.QRect(10, 750, 311, 20))
        self.cbCheckAllDevice.setObjectName("cbCheckAllDevice")
        self.tableViewScript = QtWidgets.QTableView(self.centralwidget)
        self.tableViewScript.setGeometry(QtCore.QRect(580, 360, 301, 381))
        self.tableViewScript.setObjectName("tableViewScript")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 770, 416, 81))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(440, 760, 441, 100))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonStop = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.gridLayout.addWidget(self.pushButtonStop, 1, 1, 1, 1)
        self.pushButtonReLogin = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonReLogin.setObjectName("pushButtonReLogin")
        self.gridLayout.addWidget(self.pushButtonReLogin, 1, 3, 1, 1)
        self.pushButtonReboot = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonReboot.setObjectName("pushButtonReboot")
        self.gridLayout.addWidget(self.pushButtonReboot, 1, 4, 1, 1)
        self.pushButtonRun = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonRun.setObjectName("pushButtonRun")
        self.gridLayout.addWidget(self.pushButtonRun, 1, 0, 1, 1)
        self.pushButtonUninstallDeb = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonUninstallDeb.setObjectName("pushButtonUninstallDeb")
        self.gridLayout.addWidget(self.pushButtonUninstallDeb, 2, 0, 1, 1)
        self.pushButtonUninstallApp = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonUninstallApp.setObjectName("pushButtonUninstallApp")
        self.gridLayout.addWidget(self.pushButtonUninstallApp, 2, 1, 1, 1)
        self.listViewGroup = QtWidgets.QListView(self.centralwidget)
        self.listViewGroup.setGeometry(QtCore.QRect(560, 80, 291, 251))
        self.listViewGroup.setObjectName("listViewGroup")
        self.labelGroupName = QtWidgets.QLabel(self.centralwidget)
        self.labelGroupName.setGeometry(QtCore.QRect(10, 40, 221, 49))
        self.labelGroupName.setObjectName("labelGroupName")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 893, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushBtnClearDevice.clicked.connect(MainWindow.clearDevice)
        self.pushBtnRepairTs.clicked.connect(MainWindow.repairTS)
        self.pushBtnCheckStatus.clicked.connect(MainWindow.checkStatus)
        self.pushBtnScanning.clicked.connect(MainWindow.scanningDevice)
        self.cbCheckAllDevice.clicked.connect(MainWindow.checkAllDevice)
        self.tableViewDevice.clicked['QModelIndex'].connect(MainWindow.checkClaculate)
        self.pushButtonRun.clicked.connect(MainWindow.runScript)
        self.pushButtonStop.clicked.connect(MainWindow.stopScript)
        self.pushButtonReLogin.clicked.connect(MainWindow.signOutDevice)
        self.pushButtonReboot.clicked.connect(MainWindow.rebootDevice)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditIP.setPlaceholderText(_translate("MainWindow", "请输入扫描的IP段"))
        self.pushBtnScanning.setText(_translate("MainWindow", "扫描设备"))
        self.pushBtnClearDevice.setText(_translate("MainWindow", "清空设备"))
        self.pushBtnRepairTs.setText(_translate("MainWindow", "清理脚本"))
        self.pushBtnCheckStatus.setText(_translate("MainWindow", "检测状态"))
        self.cbCheckAllDevice.setText(_translate("MainWindow", "全/反选"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "设置脚本或者插件路径"))
        self.pushButtonStop.setText(_translate("MainWindow", "停止脚本"))
        self.pushButtonReLogin.setText(_translate("MainWindow", "注销"))
        self.pushButtonReboot.setText(_translate("MainWindow", "重启"))
        self.pushButtonRun.setText(_translate("MainWindow", "运行/发送/安装"))
        self.pushButtonUninstallDeb.setText(_translate("MainWindow", "卸载插件"))
        self.pushButtonUninstallApp.setText(_translate("MainWindow", "卸载App"))
        self.labelGroupName.setText(_translate("MainWindow", "当前设备分组:"))


